Repository wecode-bootcamp-korea/18-1st-baemin-store-frontend, pull requests merged in 2021-03, with the labels that each got.

#8 [18기 김미현] Modify : 로그인 레이아웃 구현
  .eslintrc
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Order/Order.js
Labels: Status: 리뷰 요청

#7 [18기 홍래영] 상품상세페이지 기본기능 구현 완료, 장바구니 및 구매 기능 구현 중
  public/data/data.json
  src/Pages/Login/Login.js
  src/Pages/ProductDetail/Components/ItemGoodsTab/ItemGoodsTab.js
  src/Pages/ProductDetail/Components/ItemGoodsTab/ItemGoodsTab.scss
  src/Pages/ProductDetail/Components/ItemPhotoInfoSec/Components/OptionArea.js
  src/Pages/ProductDetail/Components/ItemPhotoInfoSec/Components/OptionArea.scss
  src/Pages/ProductDetail/Components/ItemPhotoInfoSec/ItemPhotoInfoSec.js
  src/Pages/ProductDetail/Components/ItemPhotoInfoSec/ItemPhotoInfoSec.scss
  src/Pages/ProductDetail/Components/Review/Review.js
  src/Pages/ProductDetail/Components/Review/Review.scss
  src/Pages/ProductDetail/Components/TableElements/TableElements.js
  src/Pages/ProductDetail/Productdetail.js
  src/Pages/ProductDetail/Productdetail.scss
  src/Styles/common.scss
Labels: Status: 리뷰 요청

#6 [18기 최송희] Add : 헤더 및 상품 컴포넌트 레이아웃 작업 완료, CSS 이벤트 속성 작업 중
  public/Images/logo_main.png
  public/Images/slide1.png
  public/Images/slide2.png
  public/Images/slide3.png
  public/data/products.json
  public/index.html
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/Product/Product.js
  src/Components/Product/Product.scss
  src/Pages/CatProdudctList/CatProdudctList.js
  src/Pages/CatProdudctList/CatProdudctList.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/ProductsList/ProductsList.js
  src/Pages/Main/ProductsList/ProductsList.scss
  src/Pages/Main/SlideBanner/SlideBanner.js
  src/Pages/Main/SlideBanner/SlideBanner.scss
  src/Routes.js
  src/Styles/common.scss
Labels: Status: 리뷰 요청

#15 [18기 홍래영] Modify : input 수량 입력 조건문 수정
  src/Pages/ProductDetail/Components/ItemPhotoInfoSec/ItemPhotoInfoSec.js
Labels: Status: Accepted

#12 [18기 김미현]회원가입(signup)페이지 레이아웃 완료/유효성 기능구현 중
  package-lock.json
  package.json
  public/Images/footer_logo.png
  public/data/iddb.json
  public/index.html
  src/Pages/Cart/Cart.js
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/SignUp/SignUp.scss
  src/Pages/SignUp/Signup.js
  src/Pages/SignUp/SignupProcess.js
  src/Pages/SignUp/SignupProcess.scss
  src/Routes.js
Labels: Status: Accepted

#10 [18기 김미현] Feature/footer
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Footer/footerLogo.png
  src/Routes.js
Labels: Status: Accepted

#13 [18기 홍래영] 장바구니 기본 기능 구현 완료, 서버와 통신 확인 예정/컨플릭트 해결
  public/data/cartData.json
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Cart/Components/CartItem/CartItem.js
  src/Pages/Cart/Components/CartItem/CartItem.scss
  src/Pages/Cart/Components/OptionModal/OptionModal.js
  src/Pages/Cart/Components/OptionModal/OptionModal.scss
Labels: Status: Accepted

#14 [18기 김미현] Feature/wishlist
  public/data/wishlistItems.json
  src/Pages/Wishlist/Wishlist.js
  src/Pages/Wishlist/Wishlist.scss
  src/Pages/Wishlist/WishlistItem.js
  src/Pages/Wishlist/product1.JPG
  src/Routes.js
Labels: Status: 리뷰 요청

#16 [18기 홍래영] Modify : 주소 경로 수정 및 일부 scss 수정
  src/Pages/ProductDetail/Components/ItemGoodsTab/ItemGoodsTab.scss
  src/Pages/ProductDetail/Components/ItemPhotoInfoSec/ItemPhotoInfoSec.js
  src/Pages/ProductDetail/Productdetail.js
  src/Pages/ProductDetail/Productdetail.scss
  src/config.js
Labels: Status: 리뷰 요청

#17 [18기 김미현] login _ 충돌사항 수정
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
Labels: Status: 리뷰 요청

#20 [18기 최송희] 메인페이지 내 타 페이지 이동 구현 완료
  src/Components/Header/Header.js
  src/Components/Header/SearchBox/SearchBox.js
  src/Components/Header/SearchBox/SearchBox.scss
  src/Components/Product/Product.js
  src/Pages/CatProdudctList/CatProdudctList.js
  src/Pages/CatProdudctList/CatProdudctList.scss
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Pages/Main/ProductsList/ProductsList.js
  src/Pages/Main/ProductsList/ProductsList.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#21 [18기 홍래영] Modify : 상품상세, 장바구니 최종발표 전 수정
  src/Components/Header/Header.js
  src/Pages/Cart/Cart.js
  src/Pages/Login/Login.scss
  src/Pages/ProductDetail/Components/ItemPhotoInfoSec/ItemPhotoInfoSec.js
  src/Pages/ProductDetail/Components/Review/Review.js
  src/Pages/ProductDetail/Productdetail.js
  src/Pages/ProductDetail/Productdetail.scss
  src/Pages/SignUp/SignUp.scss
  src/Pages/SignUp/SignupProcess.scss
  src/config.js
Labels: Status: 리뷰진행중

#22 [배민store 프론트앤드] 작업 최종 확인 완료
  src/Components/Header/Header.js
  src/Components/Product/Product.js
  src/Pages/Cart/Cart.js
  src/Pages/CatProdudctList/CatProdudctList.js
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Pages/Order/Order.js
  src/Pages/Order/Order.scss
  src/Pages/Order/OrderItem.js
  src/Pages/ProductDetail/Components/ItemPhotoInfoSec/ItemPhotoInfoSec.js
  src/Pages/SignUp/SignUp.scss
  src/Pages/SignUp/Signup.js
  src/Pages/SignUp/SignupProcess.js
  src/Pages/Wishlist/Wishlist.js
  src/Pages/Wishlist/Wishlist.scss
  src/Pages/Wishlist/WishlistItem.js
Labels: Status: 리뷰 요청

#23 [배민store 프론트엔드] MODIFY : config 파일로 서버 주소 분리
  src/Components/Product/Product.js
  src/Pages/CatProdudctList/CatProdudctList.js
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Pages/Order/Order.js
  src/Pages/ProductDetail/Productdetail.js
  src/Pages/SignUp/SignupProcess.js
  src/Pages/Wishlist/Wishlist.js
  src/config.js
Labels: Status: 리뷰 요청
